spring.ai.azure.openai.api-key=${DIAL_API_KEY}
spring.ai.azure.openai.endpoint=https://ai-proxy.lab.epam.com
spring.ai.azure.openai.embedding.options.deployment-name=text-embedding-3-small-1

logging.level.org.springframework.web=TRACE
logging.level.com.azure.ai.openai=DEBUG
logging.level=TRACE
logging.level.org.springframework.web.reactive.function.client=TRACE
logging.level.reactor.netty.http.client=TRACE

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.ai.mcp.client.sse.connections.generalPurposeAgent.url=http://localhost:8081
spring.ai.mcp.client.sse.connections.umsAgent.url=http://localhost:8082

spring.ai.mcp.client.stdio.root-change-notification=true
spring.sql.init.mode=always
