version: '3.8'
services:

  postgres:
    image: pgvector/pgvector:pg13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ddg-search:
    image: khshanovskyi/ddg-mcp-server:latest
    ports:
      - "8051:8000"
    environment:
      LOG_LEVEL: "INFO"
      MCP_TRANSPORT: "streamable-http"
    restart: unless-stopped
    mem_limit: 512M
    cpus: 0.5

  python-interpreter:
    image: khshanovskyi/python-code-interpreter-mcp-server:latest
    ports:
      - "8050:8000"
    environment:
      LOG_LEVEL: "INFO"
    restart: unless-stopped
    mem_limit: 2G
    cpus: 2.0


volumes:
  postgres_data:

